author:
        name: Microsoft

description: Use SQL Server 2016 + R Services to build and deploy a machine learning model for loan credit risk.

# site variables
solution_name: Fraud Detection 
folder_name: Fraud
db_name: Fraud
ps1_name: OnlineFraudDetection.ps1
sql_image_url: images/fraudsql.jpg
hdi_image_url: images/fraudhdi.jpg
jupyter_name: XXX.ipynb

cig_text: SQL Server 2016 on Azure
onp_text: SQL Server 2016 On-Prem 
hdi_text: HDInsight Spark 

# urls, etc
code_url: "https://github.com/Microsoft/r-server-fraud-detection"
website_url: "https://microsoft.github.io/r-server-fraud-detection"  
deploy_url: "https://aka.ms/fraud-detection" 
deploy_url_hdi: "https://aka.ms/fraud-detection-hdi" 
pbix_name: onlinefraud.pbix
hdipbix_name: "onlinefraudHDI.pbx"
pbix_hdidownload_url: "https://github.com/Microsoft/r-server-loan-credit-risk/blob/master/onlinefraudHDI.pbix"
pbix_sqldownload_url: "https://github.com/Microsoft/r-server-loan-credit-risk/blob/master/onlinefraud.pbix"
pbix_view_url: "https://start.cortanaintelligence.com/TryItNow/Dashboard/frauddetection"
pbix_hdiview_url: "https://start.cortanaintelligence.com/TryItNow/Dashboard/frauddetection"
